### PR TITLE
feature: Add cicd pipleine

### PR DESCRIPTION
**Pull request by aakhtar3**

### CODE REVIEW

**Comment by aakhtar3** [comment]
@Fleker Added this GH action to your repo

**Comment by Fleker** [comment]
Thanks for creating this PR. Right now the repo is setup so that build files are committed to `dist/app` for hosting via GitHub pages. Is there a way for GitHub to automatically do this via Actions so that the developer does not need to commit build files manually?

**Comment by aakhtar3** [comment]
Yes, you can include dist in the .gitignore file and add on to this GitHub action or create a separate action.

**Comment by Fleker** [comment]
Can you include this in this GH action?

**Comment by aakhtar3** [comment]
I can add the .gitignore change, but to enable a GH action to do the automation, it will need permission which I don't have.

**Comment by Fleker** [comment]
How do I give it that kind of permission?

**Comment by aakhtar3** [comment]
You can create the tokens that I need the automation to do or make an admin of this repo.
FYI, this PR was more scoped to give you a CICD process to prevent merging code that is unable to run npm build by running it against pull requests.

**Comment by Fleker** [comment]
Sure and I can probably merge your PR now and then follow-up with deployment later. Is there a good guide or example you know of that I'll be able to do?

**Comment by aakhtar3** [comment]
It’s not that simple, but you can create a deploy key for your repo and register it as a secret.
Here is an example, but don’t need to follow this approach.
https://github.com/marketplace/actions/deploy-to-github-pages

**Comment by Fleker** [comment]
Found a good action that I've been able to incorporate automatically.

**Pull request merged**
